name: Docker Image Publish Workflow

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build . --tag aslanhattukai/pub-dockerkedro:latest

      - name: Publish Docker image
        run: docker push aslanhattukai/pub-dockerkedro:latest
