name: Docker Image Publish Workflow

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build and publish Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: AslanHattukai/pub-DockerKedro:latest
          registry: docker.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the Docker image
        run: |
          docker build . --tag docker.io/AslanHattukaiDHV/pub-DockerKedro:latest
          docker run docker.io/AslanHattukaiDHV/pub-DockerKedro:latest
          docker push docker.io/AslanHattukaiDHV/pub-DockerKedro:latest
